apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: canary
  description: Hello world style services that platform team can use to ensure operations of the platform.
spec:
  owner: platform-team
  domain: platform-domain
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello
  description: Simple spring-boot java app demonstrating hello world capability
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=hello
    backstage.io/source-location: url:https://github.com/tanzu-end-to-end/trp-tanzu-java-web-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: canary
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: appsso-starter-java
  description: Simple spring-boot java app demonstrating TAP app sso capability
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=appsso-starter-java
    backstage.io/source-location: url:https://github.com/tanzu-end-to-end/trp-appsso-starter-java
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: canary
---

