apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: animal-rescue
  description: Animal Rescue Application
spec:
  owner: dev-team-2
  domain: acme-internal-apps
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: animal-rescue-front-end
  description: Animal Rescue Front End
  tags:
    - microservice
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=animal-rescue-front-end'
spec:
  type: service
  lifecycle: alpha
  owner: dev-team-2
  system: animal-rescue
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: animal-rescue-back-end
  description: Animal Rescue Back End
  tags:
    - microservice
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=animal-rescue-back-end'
spec:
  type: service
  providesApis:
    - animal-rescue-api
  lifecycle: alpha
  owner: dev-team-2
  system: animal-rescue
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: animal-rescue-gateway
  description: Tanzu Spring Cloud Gateway
spec:
  type: database
  owner: platform-team
  system: animal-rescue
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: animal-rescue-postgres
  description: Tanzu SQL Postgres Database
spec:
  type: database
  owner: platform-team
  system: animal-rescue
